name: "CGate to MQTT"
description: "Clipsal CBUS to MQTT via C-Gate"
version: "0.1.7"
slug: "cgate2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
host_network: true
options:
  cgate_host:
schema:
  cgate_host: "str"
  mqtt_host: "str?"
  mqtt_port: "int(2,6)?"
  mqtt_user: "str?"
  mqtt_pass: "str?"
